### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by dongpu1813** [mastermind4242/tubaclecoin#1]
addnode=？？？

**Comment by mastermind4242** [comment]
still under development
i will update live ip's for addnode soon...

**Comment by dongpu1813** [comment]
Update addnode IP notification

**Comment by dongpu1813** [comment]
addnode=???

tubaclecoin | tubacle | scrypt | ERROR Empty reply from server
-- | -- | -- | --

**Comment by mastermind4242** [comment]
still under development.
